AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'app

  Sample SAM Template for app

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  AppStage:
    Type: String
    Default: api
  UploadLimitInMb:
    Type: Number
    Default: 5
    Description: Maximum Upload Size in Megabytes.
    MinValue: 1
    MaxValue: 100
  ContactEmailAddress:
    Type: String
    Description: Email address for operational notifications
    Default: ''
  ThumbnailWidth:
    Type: Number
    Default: 300
    Description: Thumbnail width in pixels
    MinValue: 10
    MaxValue: 1000
Conditions:
  ContactEmailSet:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ContactEmailAddress
Resources:
  UploadS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  ThumbnailsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: AppStage
  NotifyAdmins:
    Type: AWS::SNS::Topic
  AlarmNotifyOpsSubscription:
    Type: AWS::SNS::Subscription
    Condition: ContactEmailSet
    Properties:
      Endpoint:
        Ref: ContactEmailAddress
      Protocol: email
      TopicArn:
        Ref: NotifyAdmins
  ShowFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-app-dep/0ce239a0ccd94c7360a73688a40c987f
      Handler: show-form.lambdaHandler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Events:
        ShowForm:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: WebApi
      Environment:
        Variables:
          UPLOAD_S3_Bucket:
            Ref: UploadS3Bucket
          UPLOAD_LIMIT_IN_MB:
            Ref: UploadLimitInMb
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: UploadS3Bucket
  ConfirmUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-app-dep/f1cdc5e76782f51bf43e23353f2c33a9
      Handler: confirm-upload.lambdaHandler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Events:
        ConfirmForm:
          Type: Api
          Properties:
            Path: /confirm
            Method: get
            RestApiId:
              Ref: WebApi
      Environment:
        Variables:
          UPLOAD_S3_Bucket:
            Ref: ThumbnailsS3Bucket
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: ThumbnailsS3Bucket
  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-app-dep/a0523b036807bb4da4358db9338a941a
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Events:
        FileUploaded:
          Type: S3
          Properties:
            Bucket:
              Ref: UploadS3Bucket
            Events: s3:ObjectCreated:*
      Timeout: 600
      MemorySize: 1024
      Environment:
        Variables:
          OUTPUT_BUCKET:
            Ref: ThumbnailsS3Bucket
          THUMB_WIDTH:
            Ref: ThumbnailWidth
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: ThumbnailsS3Bucket
      DeadLetterQueue:
        Type: SNS
        TargetArn:
          Ref: NotifyAdmins
      Layers:
      - Fn::GetAtt:
        - ImageMagick
        - Outputs.LayerVersion
  ConvertFunctionCanReadUploads:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ConvertFunctionCanReadUploads
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
          - Fn::Sub: ${UploadS3Bucket.Arn}/*
      Roles:
      - Ref: ConvertFileFunctionRole
  HelloWorldErrors:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 5
      Period: 60
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Namespace: AWS/Lambda
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: ShowFormFunction
  ImageMagick:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer
        SemanticVersion: 1.0.0
Outputs:
  UserFormApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
  ShowFormFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ShowFormFunction
      - Arn
  ShowFormFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - ShowFormFunctionRole
      - Arn
  UploadBucket:
    Description: S3 Bucket for user information
    Value:
      Ref: UploadS3Bucket
